
CREATE TABLE D41_USER_PARTNER
(
  OBJECT_ID           NUMBER(27)                                 NOT NULL,
  CLIENT_ID           NUMBER(27)                                 NOT NULL,
  CREATED             DATE,
  CHANGED             DATE,
  CREATEDBY           VARCHAR2(10 CHAR),
  CHANGEDBY           VARCHAR2(10 CHAR),
  CREATEDON           VARCHAR2(100 CHAR),
  CHANGEDON           VARCHAR2(100 CHAR),
  USER_ID             NUMBER(27)                                 NOT NULL,
  PARTNER_NUMBER      VARCHAR2(10 CHAR)                          NOT NULL
)
TABLESPACE DOC41WEB_DAT
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE UNIQUE INDEX PK_D41_USER_PARTNER ON D41_USER_PARTNER
(OBJECT_ID)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX UK_D41_USER_PARTNER ON D41_USER_PARTNER
(USER_ID, PARTNER_NUMBER)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE OR REPLACE TRIGGER D41_USER_PARTNER_CDT
BEFORE INSERT OR UPDATE ON
  DOC41WEB_MGR.D41_USER_PARTNER
FOR EACH ROW
DECLARE
--  declare variables...
BEGIN
--  protect the create columns
  IF (INSERTING) THEN
    :new.created := DOC41WEB_FDT.get_Normalized_Time();
    IF (:new.changedBy IS NULL) THEN
      :new.changedBy := :new.createdBy;
    END IF;
  END IF;
  IF (UPDATING) THEN
    :new.created   := :old.created;
    :new.createdBy := :old.createdBy;
    :new.createdOn := :old.createdOn;
  END IF;
  :new.changed := DOC41WEB_FDT.get_Normalized_Time();
  IF (INSERTING AND :new.object_Id IS NULL) THEN
    :new.object_Id := DOC41WEB_FDT.get_Next_Oid();
  ELSIF (UPDATING) THEN
    :new.object_Id := :old.object_Id;
  END IF;
END;
/
SHOW ERRORS;

ALTER TABLE D41_USER_PARTNER ADD (
  CONSTRAINT PK_D41_USER_PARTNER
 PRIMARY KEY
 (OBJECT_ID));

ALTER TABLE D41_USER_PARTNER ADD (
  CONSTRAINT UK_D41_USER_PARTNER
 UNIQUE
 (USER_ID, PARTNER_NUMBER));

ALTER TABLE D41_USER_PARTNER ADD (
  CONSTRAINT FK_D41_USER_PARTNER_USER
 FOREIGN KEY (USER_ID)
 REFERENCES DOC41WEB_FDT.UM_USERS (OBJECT_ID)
);

GRANT DELETE, INSERT, SELECT, UPDATE             ON D41_USER_PARTNER TO MXDOC41WEB WITH GRANT OPTION;


CREATE TABLE MD_DOCUMENT_TYPE
(
  OBJECT_ID              NUMBER(27)                                 NOT NULL,
  CREATED                DATE,
  CHANGED                DATE,
  CREATEDBY              VARCHAR2(10 CHAR),
  CHANGEDBY              VARCHAR2(10 CHAR),
  CREATEDON              VARCHAR2(100 CHAR),
  CHANGEDON              VARCHAR2(100 CHAR),
  OBJECTSTATE_ID         NUMBER(2)                 DEFAULT 1        NOT NULL,
  DOCUMENT_TYPE          VARCHAR2(100 CHAR)                         NOT NULL,
  IS_DOWNLOAD            NUMBER(1)                 DEFAULT 0        NOT NULL CONSTRAINT CK_MD_DT_ISDL CHECK (IS_DOWNLOAD IN (0, 1)),
  IS_UPLOAD              NUMBER(1)                 DEFAULT 0        NOT NULL CONSTRAINT CK_MD_DT_ISUL CHECK (IS_UPLOAD IN (0, 1)),
  BUSINESS_UNIT          VARCHAR2(20 CHAR)
)
TABLESPACE DOC41WEB_DAT
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE UNIQUE INDEX PK_MD_DOCUMENT_TYPE ON MD_DOCUMENT_TYPE
(OBJECT_ID)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX UK_MD_DOCUMENT_TYPE ON MD_DOCUMENT_TYPE
(DOCUMENT_TYPE)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE OR REPLACE TRIGGER MD_DOCUMENT_TYPE_CDT
BEFORE INSERT OR UPDATE ON
  DOC41WEB_MGR.MD_DOCUMENT_TYPE
FOR EACH ROW
DECLARE
--  declare variables...
BEGIN
--  protect the create columns
  IF (INSERTING) THEN
    :new.created := DOC41WEB_FDT.get_Normalized_Time();
    IF (:new.changedBy IS NULL) THEN
      :new.changedBy := :new.createdBy;
    END IF;
  END IF;
  IF (UPDATING) THEN
    :new.created   := :old.created;
    :new.createdBy := :old.createdBy;
    :new.createdOn := :old.createdOn;
  END IF;
  :new.changed := DOC41WEB_FDT.get_Normalized_Time();
  IF (INSERTING AND :new.object_Id IS NULL) THEN
    :new.object_Id := DOC41WEB_FDT.get_Next_Oid();
  ELSIF (UPDATING) THEN
    :new.object_Id := :old.object_Id;
  END IF;
END;
/
SHOW ERRORS;

ALTER TABLE MD_DOCUMENT_TYPE ADD (
  CONSTRAINT PK_MD_DOCUMENT_TYPE
 PRIMARY KEY
 (OBJECT_ID));

ALTER TABLE MD_DOCUMENT_TYPE ADD (
  CONSTRAINT UK_MD_DOCUMENT_TYPE
 UNIQUE
 (DOCUMENT_TYPE));

ALTER TABLE MD_DOCUMENT_TYPE ADD (
  CONSTRAINT FK_MD_DOCUMENT_TYPE_OS
 FOREIGN KEY (OBJECTSTATE_ID)
 REFERENCES DOC41WEB_FDT.OBJECTSTATE (OBJECTSTATE_ID)
 );

GRANT DELETE, INSERT, SELECT, UPDATE             ON MD_DOCUMENT_TYPE TO MXDOC41WEB WITH GRANT OPTION;

CREATE TABLE MD_SYSPARAM
(
  OBJECT_ID              NUMBER(27)                                 NOT NULL,
  CREATED                DATE,
  CHANGED                DATE,
  CREATEDBY              VARCHAR2(10 CHAR),
  CHANGEDBY              VARCHAR2(10 CHAR),
  CREATEDON              VARCHAR2(100 CHAR),
  CHANGEDON              VARCHAR2(100 CHAR),
  PARAM_NAME             VARCHAR2(50 CHAR)                          NOT NULL,
  PARAM_TYPE             VARCHAR2(20 CHAR)                          NOT NULL,
  PARAM_STRINGVALUE      VARCHAR2(500 CHAR),
  PARAM_NUMBERVALUE      NUMBER(27),
  PARAM_DECIMALVALUE     NUMBER(15,3),
  PARAM_BOOLEANVALUE     NUMBER(1)                                           CONSTRAINT CK_MD_SYSPARAM_BOOL  CHECK (PARAM_BOOLEANVALUE IN (0, 1)),
  IS_DELETABLE           NUMBER(1)            DEFAULT 1             NOT NULL CONSTRAINT CK_MD_SYSPARAM_ISDEL CHECK (IS_DELETABLE IN (0, 1))
)
TABLESPACE DOC41WEB_DAT
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE UNIQUE INDEX PK_MD_SYSPARAM ON MD_SYSPARAM
(OBJECT_ID)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX UK_MD_SYSPARAM ON MD_SYSPARAM
(PARAM_NAME)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE OR REPLACE TRIGGER MD_SYSPARAM_CDT
BEFORE INSERT OR UPDATE ON
  DOC41WEB_MGR.MD_SYSPARAM
FOR EACH ROW
DECLARE
--  declare variables...
BEGIN
--  protect the create columns
  IF (INSERTING) THEN
    :new.created := DOC41WEB_FDT.get_Normalized_Time();
    IF (:new.changedBy IS NULL) THEN
      :new.changedBy := :new.createdBy;
    END IF;
  END IF;
  IF (UPDATING) THEN
    :new.created   := :old.created;
    :new.createdBy := :old.createdBy;
    :new.createdOn := :old.createdOn;
  END IF;
  :new.changed := DOC41WEB_FDT.get_Normalized_Time();
  IF (INSERTING AND :new.object_Id IS NULL) THEN
    :new.object_Id := DOC41WEB_FDT.get_Next_Oid();
  ELSIF (UPDATING) THEN
    :new.object_Id := :old.object_Id;
  END IF;
END;
/
SHOW ERRORS;

ALTER TABLE MD_SYSPARAM ADD (
  CONSTRAINT PK_MD_SYSPARAM
 PRIMARY KEY
 (OBJECT_ID));

ALTER TABLE MD_SYSPARAM ADD (
  CONSTRAINT UK_MD_SYSPARAM
 UNIQUE
 (PARAM_NAME));

GRANT DELETE, INSERT, SELECT, UPDATE ON MD_SYSPARAM TO MXDOC41WEB WITH GRANT OPTION;


CREATE TABLE D41_CR_PROFILE_DOCTYPE
(
  OBJECT_ID           NUMBER(27)                                 NOT NULL,
  CLIENT_ID           NUMBER(27)                                 NOT NULL,
  CREATED             DATE,
  CHANGED             DATE,
  CREATEDBY           VARCHAR2(10 CHAR),
  CHANGEDBY           VARCHAR2(10 CHAR),
  CREATEDON           VARCHAR2(100 CHAR),
  CHANGEDON           VARCHAR2(100 CHAR),
  PROFILE_ID          NUMBER(27)                                 NOT NULL,
  DOCTYPE_ID          NUMBER(27)                                 NOT NULL
)
TABLESPACE DOC41WEB_DAT
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE UNIQUE INDEX PK_D41_CR_PROFILE_DOCTYPE ON D41_CR_PROFILE_DOCTYPE
(OBJECT_ID)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX UK_D41_CR_PROFILE_DOCTYPE ON D41_CR_PROFILE_DOCTYPE
(PROFILE_ID, DOCTYPE_ID)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE OR REPLACE TRIGGER D41_CR_PROFILE_DOCTYPE_CDT
BEFORE INSERT OR UPDATE ON
  DOC41WEB_MGR.D41_CR_PROFILE_DOCTYPE
FOR EACH ROW
DECLARE
--  declare variables...
BEGIN
--  protect the create columns
  IF (INSERTING) THEN
    :new.created := DOC41WEB_FDT.get_Normalized_Time();
    IF (:new.changedBy IS NULL) THEN
      :new.changedBy := :new.createdBy;
    END IF;
  END IF;
  IF (UPDATING) THEN
    :new.created   := :old.created;
    :new.createdBy := :old.createdBy;
    :new.createdOn := :old.createdOn;
  END IF;
  :new.changed := DOC41WEB_FDT.get_Normalized_Time();
  IF (INSERTING AND :new.object_Id IS NULL) THEN
    :new.object_Id := DOC41WEB_FDT.get_Next_Oid();
  ELSIF (UPDATING) THEN
    :new.object_Id := :old.object_Id;
  END IF;
END;
/
SHOW ERRORS;

ALTER TABLE D41_CR_PROFILE_DOCTYPE ADD (
  CONSTRAINT PK_D41_CR_PROFILE_DOCTYPE
 PRIMARY KEY
 (OBJECT_ID));

ALTER TABLE D41_CR_PROFILE_DOCTYPE ADD (
  CONSTRAINT UK_D41_CR_PROFILE_DOCTYPE
 UNIQUE
 (PROFILE_ID, DOCTYPE_ID));

ALTER TABLE D41_CR_PROFILE_DOCTYPE ADD (
  CONSTRAINT FK_D41_CR_PROFILE_DOCTYPE_PROF
 FOREIGN KEY (PROFILE_ID)
 REFERENCES DOC41WEB_FDT.UM_PROFILES (OBJECT_ID),
  CONSTRAINT FK_D41_CR_PROFILE_DOCTYPE_DOCT
 FOREIGN KEY (DOCTYPE_ID)
 REFERENCES DOC41WEB_MGR.MD_DOCUMENT_TYPE (OBJECT_ID)
);

GRANT DELETE, INSERT, SELECT, UPDATE             ON D41_CR_PROFILE_DOCTYPE TO MXDOC41WEB WITH GRANT OPTION;


CREATE TABLE IM_INTERFACE_DETAIL
(
  OBJECT_ID              NUMBER(27)                                 NOT NULL,
  CREATED                DATE,
  CHANGED                DATE,
  CREATEDBY              VARCHAR2(10 CHAR),
  CHANGEDBY              VARCHAR2(10 CHAR),
  CREATEDON              VARCHAR2(100 CHAR),
  CHANGEDON              VARCHAR2(100 CHAR),
  INTERFACE_NAME         VARCHAR2(50 CHAR)                          NOT NULL,
  INTERFACE_DESCRIPTION  VARCHAR2(200 CHAR)
)
TABLESPACE DOC41WEB_DAT
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE UNIQUE INDEX PK_IM_INTERFACE_DETAIL ON IM_INTERFACE_DETAIL
(OBJECT_ID)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX UK_IM_INTERFACE_DETAIL ON IM_INTERFACE_DETAIL
(INTERFACE_NAME)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE OR REPLACE TRIGGER IM_INTERFACE_DETAIL_CDT
BEFORE INSERT OR UPDATE ON
  DOC41WEB_MGR.IM_INTERFACE_DETAIL
FOR EACH ROW
DECLARE
--  declare variables...
BEGIN
--  protect the create columns
  IF (INSERTING) THEN
    :new.created := DOC41WEB_FDT.get_Normalized_Time();
    IF (:new.changedBy IS NULL) THEN
      :new.changedBy := :new.createdBy;
    END IF;
  END IF;
  IF (UPDATING) THEN
    :new.created   := :old.created;
    :new.createdBy := :old.createdBy;
    :new.createdOn := :old.createdOn;
  END IF;
  :new.changed := DOC41WEB_FDT.get_Normalized_Time();
  IF (INSERTING AND :new.object_Id IS NULL) THEN
    :new.object_Id := DOC41WEB_FDT.get_Next_Oid();
  ELSIF (UPDATING) THEN
    :new.object_Id := :old.object_Id;
  END IF;
END;
/
SHOW ERRORS;

ALTER TABLE IM_INTERFACE_DETAIL ADD (
  CONSTRAINT PK_IM_INTERFACE_DETAIL
 PRIMARY KEY
 (OBJECT_ID));

ALTER TABLE IM_INTERFACE_DETAIL ADD (
  CONSTRAINT UK_IM_INTERFACE_DETAIL
 UNIQUE
 (INTERFACE_NAME));

GRANT DELETE, INSERT, SELECT, UPDATE ON IM_INTERFACE_DETAIL TO MXDOC41WEB WITH GRANT OPTION;


CREATE TABLE IM_MONITORING_CONTACT
(
  OBJECT_ID              NUMBER(27)                                 NOT NULL,
  CREATED                DATE,
  CHANGED                DATE,
  CREATEDBY              VARCHAR2(10 CHAR),
  CHANGEDBY              VARCHAR2(10 CHAR),
  CREATEDON              VARCHAR2(100 CHAR),
  CHANGEDON              VARCHAR2(100 CHAR),
  INTERFACE_NAME         VARCHAR2(50 CHAR)                          NOT NULL,
  CONTACT_TYPE           VARCHAR2(20 CHAR)                          NOT NULL,
  CWID                   VARCHAR2(10 CHAR)                          NOT NULL,
  FIRST_NAME             VARCHAR2(30 CHAR)                          NOT NULL,
  LAST_NAME              VARCHAR2(70 CHAR)                          NOT NULL,
  EMAIL                  VARCHAR2(70 CHAR)                          NOT NULL,
  PHONE1                 VARCHAR2(35 CHAR)                          NOT NULL,
  PHONE2                 VARCHAR2(35 CHAR)
)
TABLESPACE DOC41WEB_DAT
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE UNIQUE INDEX PK_IM_MONITORING_CONTACT ON IM_MONITORING_CONTACT
(OBJECT_ID)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX UK_IM_MONITORING_CONTACT ON IM_MONITORING_CONTACT
(INTERFACE_NAME, CWID)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE OR REPLACE TRIGGER IM_MONITORING_CONTACT_CDT
BEFORE INSERT OR UPDATE ON
  DOC41WEB_MGR.IM_MONITORING_CONTACT
FOR EACH ROW
DECLARE
--  declare variables...
BEGIN
--  protect the create columns
  IF (INSERTING) THEN
    :new.created := DOC41WEB_FDT.get_Normalized_Time();
    IF (:new.changedBy IS NULL) THEN
      :new.changedBy := :new.createdBy;
    END IF;
  END IF;
  IF (UPDATING) THEN
    :new.created   := :old.created;
    :new.createdBy := :old.createdBy;
    :new.createdOn := :old.createdOn;
  END IF;
  :new.changed := DOC41WEB_FDT.get_Normalized_Time();
  IF (INSERTING AND :new.object_Id IS NULL) THEN
    :new.object_Id := DOC41WEB_FDT.get_Next_Oid();
  ELSIF (UPDATING) THEN
    :new.object_Id := :old.object_Id;
  END IF;
END;
/
SHOW ERRORS;

ALTER TABLE IM_MONITORING_CONTACT ADD (
  CONSTRAINT PK_IM_MONITORING_CONTACT
 PRIMARY KEY
 (OBJECT_ID));

ALTER TABLE IM_MONITORING_CONTACT ADD (
  CONSTRAINT UK_IM_MONITORING_CONTACT
 UNIQUE
 (INTERFACE_NAME, CWID));

GRANT DELETE, INSERT, SELECT, UPDATE ON IM_MONITORING_CONTACT TO MXDOC41WEB WITH GRANT OPTION;

CREATE TABLE IM_MONITORING_HISTORY
(
  OBJECT_ID              NUMBER(27)                                 NOT NULL,
  CREATED                DATE,
  CHANGED                DATE,
  CREATEDBY              VARCHAR2(10 CHAR),
  CHANGEDBY              VARCHAR2(10 CHAR),
  CREATEDON              VARCHAR2(100 CHAR),
  CHANGEDON              VARCHAR2(100 CHAR),
  INTERFACE_NAME         VARCHAR2(50 CHAR)                          NOT NULL,
  LATEST_REQUEST         TIMESTAMP                                  NOT NULL,
  ACTION_TYPE            VARCHAR2(25 CHAR)                          NOT NULL,
  ACTION_STATUS          VARCHAR2(10 CHAR),
  ACTION_REMARKS         VARCHAR2(100 CHAR),
  ACTION_DETAILS         VARCHAR2(250 CHAR),
  RESPONSE_TIME          NUMBER
)
TABLESPACE DOC41WEB_DAT
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE UNIQUE INDEX PK_IM_MONITORING_HISTORY ON IM_MONITORING_HISTORY
(OBJECT_ID)
TABLESPACE DOC41WEB_IDX
LOGGING
NOPARALLEL;

CREATE OR REPLACE TRIGGER IM_MONITORING_HISTORY_CDT
BEFORE INSERT OR UPDATE ON
  DOC41WEB_MGR.IM_MONITORING_HISTORY
FOR EACH ROW
DECLARE
--  declare variables...
BEGIN
--  protect the create columns
  IF (INSERTING) THEN
    :new.created := DOC41WEB_FDT.get_Normalized_Time();
    IF (:new.changedBy IS NULL) THEN
      :new.changedBy := :new.createdBy;
    END IF;
  END IF;
  IF (UPDATING) THEN
    :new.created   := :old.created;
    :new.createdBy := :old.createdBy;
    :new.createdOn := :old.createdOn;
  END IF;
  :new.changed := DOC41WEB_FDT.get_Normalized_Time();
  IF (INSERTING AND :new.object_Id IS NULL) THEN
    :new.object_Id := DOC41WEB_FDT.get_Next_Oid();
  ELSIF (UPDATING) THEN
    :new.object_Id := :old.object_Id;
  END IF;
END;
/
SHOW ERRORS;

ALTER TABLE IM_MONITORING_HISTORY ADD (
  CONSTRAINT PK_IM_MONITORING_HISTORY
 PRIMARY KEY
 (OBJECT_ID));

GRANT DELETE, INSERT, SELECT, UPDATE ON IM_MONITORING_HISTORY TO MXDOC41WEB WITH GRANT OPTION;
