INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'NavSupportConsole',
  'Show Navigation Entry Support Console',
  'NAV_SUPPORTCONSOLE'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'NavTranslations',
  'Show Navigation Entry Translations',
  'NAV_TRANSLATIONS'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'NavMonitoring',
  'Show Navigation Entry Monitoring',
  'NAV_MONITORING'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'NavProfilePermissions',
  'Show Navigation Entry Profile Permissions',
  'NAV_PROFILEPERMISSIONS'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'NavRFCMetadata',
  'Show Navigation Entry RFC Metadata',
  'NAV_RFCMETADATA'
);

-- Documents
INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentBillOfLadingUpload',
  'Upload Bill of Lading',
  'DOC_BOL_UP'
);


INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentAirWaybillUpload',
  'Upload Air Waybill',
  'DOC_AWB_UP'
);


INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentTemperatureLogfileUpload',
  'Upload Temperature Logfile',
  'DOC_TEMPLOG_UP'
);


INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentCertificateOfOriginDownload',
  'Download Certificate of Origin',
  'DOC_COO_DOWN'
);


INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentCertificateOfComplianceDownload',
  'Download Certificate of Compliance',
  'DOC_COC_DOWN'
);


-- Controller
INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'AddInternalUserToLogGroup',
  'Add Internal User To Log Group',
  'ADDINTERNALUSERTOLOGGROUP'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'Monitoring',
  'Monitoring',
  'MONITORING'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'Translation',
  'Translation',
  'TRANSLATION'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'ProfilePermissions',
  'Profile Permissions View',
  'PROFILEPERMISSIONS'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'RFCMetadata',
  'RFC Metadata View',
  'RFCMETADATA'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'UserCreate',
  'User Create',
  'USER_CREATE'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'UserEdit',
  'User Edit',
  'USER_EDIT'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'UserImport',
  'User Import',
  'USER_IMPORT'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'UserList',
  'User List',
  'USER_LIST'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'UserLookup',
  'User Lookup',
  'USER_LOOKUP'
);


delete from DOC41WEB_FDT.UM_PERMISSIONS
where code='DOC_COAOUT_DOWN';

delete from DOC41WEB_FDT.UM_PERMISSIONS
where code='TOPNAV_DOCUMENTS';


delete from DOC41WEB_FDT.UM_PERMISSIONS
where code='DOC_TEMPLOG_UP';


delete from DOC41WEB_FDT.UM_PERMISSIONS
where code='DOC_COC_DOWN';



INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(PERMISSIONNAME,PERMISSIONDESCRIPTION,CODE) VALUES
('TopNavUpload','Show TopNav Entry Upload','TOPNAV_UPLOAD');

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(PERMISSIONNAME,PERMISSIONDESCRIPTION,CODE) VALUES
('TopNavDownload','Show TopNav Entry Download','TOPNAV_DOWNLOAD');

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentPackagingMaterialSpecification',
  'Download Packaging Material Specification',
  'DOC_PMS_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentTechnicalDrawingPZ',
  'Download Technical Drawing PZ',
  'DOC_PZ_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentShippersDeclaration',
  'Download Shippers Declaration',
  'DOC_SHIPDECL_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentBillofLading',
  'Download Bill of Lading',
  'DOC_BOL_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentWaybill',
  'Download Waybill',
  'DOC_WB_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentAirWaybill',
  'Download Air Waybill',
  'DOC_AWB_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentFDACertificate',
  'Download FDA Certificate',
  'DOC_FDACERT_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentSupplierCoAUpload',
  'Upload Supplier CoA',
  'DOC_SUPCOA_UP'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentCMRUpload',
  'Upload CMR',
  'DOC_CMR_UP'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentDeliveryCertificateUpload',
  'Upload Delivery Certificate',
  'DOC_DELCERT_UP'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentArtworkLowRes',
  'Download Artwork Low Res',
  'DOC_ARTWORK_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentLayoutHighResUpload',
  'Upload Layout High Res',
  'DOC_LAYOUT_UP'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentLayoutHighRes',
  'Download Layout High Res',
  'DOC_LAYOUT_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentTechPackandDelivRequirements',
  'Download Tech. Pack. and Deliv. Requirements',
  'DOC_TPACKDELREQ_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentCMROutgoing',
  'Download CMR Outgoing',
  'DOC_CMROUT_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentDeliveryCertificateCountry',
  'Download Delivery Certificate Country',
  'DOC_DELCERT_DOWN_COUNTRY'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentDeliveryCertificateCustomer',
  'Download Delivery CertificateCustomer',
  'DOC_DELCERT_DOWN_CUSTOMER'
);



INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentAirWaybillDirectDown',
  'Download Air Waybill DirectDown',
  'DOC_AWB_DIRECT_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentBillofLadingDirectDown',
  'Download Bill of Lading DirectDown',
  'DOC_BOL_DIRECT_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentWaybillDirectDown',
  'Download Waybill DirectDown',
  'DOC_WB_DIRECT_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentFDACertificateDirectDown',
  'Download FDA Certificate DirectDown',
  'DOC_FDACERT_DIRECT_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentShippersDeclarationDirectDown',
  'Download Shippers Declaration DirectDown',
  'DOC_SHIPDECL_DIRECT_DOWN'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'ReadOnly',
  'Allow only read access',
  'READ_ONLY'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'TopNavMaintenance',
  'Show TopNav Entry Maintenance',
  'TOPNAV_MAINTENANCE'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'TopNavManagement',
  'Show TopNav Entry Management',
  'TOPNAV_MANAGEMENT'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'TopNavMyProfile',
  'Show TopNav Entry My Profile',
  'TOPNAV_MYPROFILE'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'UntranslatedLabels',
  'Show Untranslated Labels View',
  'UNTRANSLATEDLABELS'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'NavUntranslatedLabels',
  'Show Navigation Untranslated Labels',
  'NAV_UNTRANSLATEDLABELS'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'NavApplogs',
  'Show Navigation Application Logs',
  'NAV_APPLOGS'
);

INSERT INTO DOC41WEB_FDT.UM_PERMISSIONS
(
  PERMISSIONNAME,
  PERMISSIONDESCRIPTION,
  CODE
)
VALUES
(
  'DocumentArtworkLowResUpload',
  'Upload Artwork Low Res',
  'DOC_ARTWORK_UP'
);