insert into DOC41WEB_FDT.UM_PGU_PERMISSIONS
(
  PERMISSION_ID,
  PROFILE_ID
) select perm.object_Id, '106006' from DOC41WEB_FDT.UM_permissions perm
  where  perm.object_Id not in (select PERMISSION_ID from DOC41WEB_FDT.UM_PGU_PERMISSIONS where profile_Id = '106006')
;

DELETE FROM DOC41WEB_FDT.UM_PGU_PERMISSIONS
 WHERE PROFILE_ID     = '106006'
   AND PERMISSION_ID IN (SELECT object_Id 
                           FROM DOC41WEB_FDT.UM_PERMISSIONS 
                          WHERE code IN ('READ_ONLY', 'CREATE_USER', 'CREATE_ADMIN', 'DOC_COAOUT_DOWN', 'TOPNAV_DOCUMENTS', 'DOC_TEMPLOG_UP', 'DOC_COC_DOWN','DOC_DELCERT_DOWN','DOC_DELCERT_UP_COUNTRY','DOC_DELCERT_UP_CUSTOMER'));
