-- admin / technical
INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,CREATED,CHANGED,CREATEDBY,CHANGEDBY,ISEXTERNAL) VALUES
('doc41_badm','Business Admin',0);

INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,CREATED,CHANGED,CREATEDBY,CHANGEDBY,ISEXTERNAL) VALUES
('doc41_tadm','Technical Admin',0);

INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,CREATED,CHANGED,CREATEDBY,CHANGEDBY,ISEXTERNAL) VALUES
('doc41_obsv','Observer',0);

-- SD
INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,ISEXTERNAL) VALUES
('doc41_carr','carrier',1);

INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,ISEXTERNAL) VALUES
('doc41_cusbr','customs broker',1);

-- PT
INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,ISEXTERNAL) VALUES
('doc41_laysup','layout supplier',1);

INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,ISEXTERNAL) VALUES
('doc41_pmsup','pm supplier',1);


--QM
INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,ISEXTERNAL) VALUES
('doc41_matsup','mat supplier',1);

INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,ISEXTERNAL) VALUES
('doc41_prodsup','product supplier',1);

INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,ISEXTERNAL) VALUES
('doc41_delcertvcountry','delivery certificate viewer country',1);

INSERT INTO DOC41WEB_FDT.UM_PROFILES
(PROFILENAME,PROFILEDESCRIPTION,ISEXTERNAL) VALUES
('doc41_delcertvcust','delivery certificate viewer customer',1);



